name: Terraform Plan

on:
    workflow_dispatch
  

jobs:
  build:
    runs-on: self-hosted  # This ensures that the self-hosted runner is used

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
     
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.1.7

      - name: Auth to AWS
        run: |
            echo "Hello, GitHub Actions!"
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Auth to AWS
        run: terraform --version
    

